root: true
env:
  node: true
  mocha: true
parserOptions:
  ecmaVersion: 2018
extends: [eslint:recommended, plugin:prettier/recommended]
rules:
  operator-assignment: [error, always]
  no-var: error
  prefer-arrow-callback: warn
  prefer-spread: warn
  no-return-await: error
  prefer-const: warn
  no-confusing-arrow: [error, allowParens: false]
  strict: error
  no-void: error
  one-var: [error, never]
  no-nested-ternary: warn
  func-style: [warn, declaration, allowArrowFunctions: true]
